apiVersion: batch/v1
kind: CronJob
metadata:
  name: soccer-summary-job
spec:
  schedule: "0 12 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: your-dockerhub/soccer-crawler:latest
          restartPolicy: OnFailure
